version: '3.8'

services:
  app-postgres-db:
    image: postgres:17
    restart: always
    container_name: app-postgres-db
    env_file: .env
    ports:
      - "5460:5432"
    volumes:
      - app-postgres-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app-postgres-db
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - golden-owl-network

  app-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: app-api
    ports:
      - "8160:8160"
    depends_on:
      - app-postgres-db
    networks:
      - golden-owl-network
    environment:
      SPRING_PROFILES_ACTIVE: "DEV"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    restart: always

networks:
  golden-owl-network:
    driver: bridge

volumes:
  app-postgres-db-data:
